### ISSUE TITLE
make test fails

### ISSUE THREAD

**Issue by alex1279** [cruise-automation/fwanalyzer#46]
seems like make test fails due to missing input binaries

**Comment by crmulliner** [comment]
can you please be more specific, thank you.

**Comment by alex1279** [comment]
hello

make deps
and
make
commands are working just finefor me. but if i am trying to do
make test
(i have tried ubuntu 18 and docker container ) - it is generating failures.
root@0df2243345bc:/go/src/github.com/cruise-automation/fwanalyzer# make test
PATH="/go/src/github.com/cruise-automation/fwanalyzer/scripts:/go/src/github.com/cruise-automation/fwanalyzer/test:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" go test -count=3 -cover ./...
ok      github.com/cruise-automation/fwanalyzer/cmd/fwanalyzer  0.007s  coverage: 23.2% of statements
ok      github.com/cruise-automation/fwanalyzer/pkg/analyzer    0.008s  coverage: 20.0% of statements
ok      github.com/cruise-automation/fwanalyzer/pkg/analyzer/dataextract        0.042s  coverage: 71.6% of statements
ok      github.com/cruise-automation/fwanalyzer/pkg/analyzer/dircontent 0.003s  coverage: 83.9% of statements
ok      github.com/cruise-automation/fwanalyzer/pkg/analyzer/filecmp    0.126s  coverage: 73.5% of statements
ok      github.com/cruise-automation/fwanalyzer/pkg/analyzer/filecontent        0.029s  coverage: 69.1% of statements
ok      github.com/cruise-automation/fwanalyzer/pkg/analyzer/filepathowner      0.015s  coverage: 45.8% of statements
ok      github.com/cruise-automation/fwanalyzer/pkg/analyzer/filestatcheck      0.047s  coverage: 68.3% of statements
ok      github.com/cruise-automation/fwanalyzer/pkg/analyzer/filetree   0.029s  coverage: 82.2% of statements
ok      github.com/cruise-automation/fwanalyzer/pkg/analyzer/globalfilechecks   0.010s  coverage: 91.5% of statements
ok      github.com/cruise-automation/fwanalyzer/pkg/capability  0.007s  coverage: 71.2% of statements
ok      github.com/cruise-automation/fwanalyzer/pkg/cpioparser  0.106s  coverage: 82.2% of statements
--- FAIL: TestGetDirInfo (0.00s)
    dirparser_test.go:50: copyfile returned false
    dirparser_test.go:53: stat /tmp/dirfs_test_file: no such file or directory
--- FAIL: TestGetFileInfo (0.00s)
    dirparser_test.go:73: GetFileInfo failed
    dirparser_test.go:76: GetFileInfo failed, isFile != true
    dirparser_test.go:82: filename does not match:
[]
--- FAIL: TestCapability (0.00s)
    dirparser_test.go:108: capability test failed: likely need to run 'sudo setcap cap_net_admin+p test/test.cap.file'
--- FAIL: TestGetDirInfo (0.00s)
    dirparser_test.go:50: copyfile returned false
    dirparser_test.go:53: stat /tmp/dirfs_test_file: no such file or directory
--- FAIL: TestGetFileInfo (0.00s)
    dirparser_test.go:73: GetFileInfo failed
    dirparser_test.go:76: GetFileInfo failed, isFile != true
    dirparser_test.go:82: filename does not match:
[]
***
my understanding this happens due to lack of  test images in the test folder...
 ls ./test/
cap_ext2.img.gz  elf_main.go     squashfs.img      test.cpio    test_cfg.base.toml     testdir       unsquashfs
e2cp             oldtree.json    squashfs_cap.img  test.img.gz  test_cfg.toml          testlink      vfat.img
e2ls             script_test.sh  test.cap.file     test.py      test_cfg_selinux.toml  ubifs.img.gz

**Comment by crmulliner** [comment]
run `make testsetup` that will prepare the test directory, will update the Build instructions

**Comment by alex1279** [comment]
Oh. Thanks. I works now...
